"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tests_1 = require("./tests");
console.log("Простейшие:");
(0, tests_1.testCompression)([1]);
(0, tests_1.testCompression)([1, 2, 3]);
(0, tests_1.testCompression)([300]);
console.log("Случайные:");
(0, tests_1.testCompression)((0, tests_1.uniqueRandom)(50));
(0, tests_1.testCompression)((0, tests_1.uniqueRandom)(100));
(0, tests_1.testCompression)((0, tests_1.uniqueRandom)(500));
(0, tests_1.testCompression)((0, tests_1.uniqueRandom)(1000));
console.log("Граничные:");
(0, tests_1.testCompression)(Array.from({ length: 9 }, (_, i) => i + 1));
(0, tests_1.testCompression)(Array.from({ length: 90 }, (_, i) => i + 10));
(0, tests_1.testCompression)(Array.from({ length: 201 }, (_, i) => i + 100));
(0, tests_1.testCompression)(Array(300).fill(0).flatMap((_, i) => [i + 1, i + 1, i + 1]).slice(0, 900));
